### ISSUE TITLE
FAILED LAUNCH BROWSER

### ISSUE THREAD

**Issue by bagusdwip** [AlenSaito1/Whatsapp-Anime-Bot#4]
error: failed to launch the browser process! spawn c:\program files (x86)\google\chrome\application\chrome.exe enoent troubleshooting: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md at onclose (c:\users\administrator\ne\node_modules\puppeteer\lib\cjs\puppeteer\node\browserrunner.js:193:20) at childprocess.<anonymous> (c:\users\administrator\ne\node_modules\puppeteer\lib\cjs\puppeteer\node\browserrunner.js:185:85) at childprocess.emit (events.js:314:20) at childprocess.eventemitter.emit (domain.js:483:12) at process.childprocess._handle.onexit (internal/child_process.js:273:12) at onerrornt (internal/child_process.js:469:16) at processticksandrejections (internal/process/task_queues.js:84:21)

help me

**Comment by shydoll-02** [comment]
I had the same p but solved already

**Comment by zencats22** [comment]
> I had the same p but solved already

How ?

**Comment by shydoll-02** [comment]
lol, 
I went to 
node_modules\puppeteer\.local-chromium\win64-809590/chrome.exe
then copied the path

**Comment by shydoll-02** [comment]
node_modules\puppeteer\.local-chromium\win64-809590\chrome-win
this
